#if(NOT CMAKE_DEBUG_POSTFIX)
#    set(CMAKE_DEBUG_POSTFIX _gd)
#endif()
if (CMAKE_COMPILER_IS_GNUCC)
    MESSAGE("is gnucc")
endif ()
MESSAGE(STATUS "c compiler :  ${CMAKE_COMPILER_IS_GNUCC}")
message(STATUS "system name : ${CMAKE_SYSTEM_NAME}")
if (${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(IS_WINDOWS 1)
    message(STATUS "host is windows")
    if (CMAKE_COMPILER_IS_GNUCC)
        set(IS_MINGW 1)
        if ("${CMAKE_BUILD_TYPE}" MATCHES "Debug")
            add_definitions("-D_DEBUG")
        endif ()
    endif ()
else()
    set(IS_LINUX 1)
    if ("${CMAKE_BUILD_TYPE}" MATCHES "Debug")
        add_definitions("-D_DEBUG")
    endif ()
    add_definitions("-Dlinux")
    message(STATUS "host is LINUX")
endif ()

set(BASEDIR "${CMAKE_BINARY_DIR}")

set(LIBRARY_OUTPUT_PATH "${BASEDIR}")